"""
Report Generation Agent — generates the full Markdown consulting report.
"""
from __future__ import annotations

import json
import logging

from backend.models.state import WorkflowState
from backend.prompts.templates import report_generation_prompt
from backend.services.gemini_client import get_llm_client
from backend.utils.helpers import make_log_entry

logger = logging.getLogger(__name__)


async def report_generation_node(state: WorkflowState) -> WorkflowState:
    """LangGraph node: Generate comprehensive Markdown business audit report."""
    log_entries = list(state.get("log_entries", []))
    log_entries.append(make_log_entry("report_generation", "started", "Generating report"))

    lead_name = state.get("lead_name", "")
    company = state.get("lead_company", "")
    website = state.get("lead_website", "")
    research = state.get("research") or {}
    analysis = state.get("analysis") or {}
    insights = state.get("insights") or {}

    try:
        llm = get_llm_client()

        research_text = json.dumps(
            {k: v for k, v in research.items() if k != "raw_web_content"},
            indent=2,
        )
        analysis_text = json.dumps(analysis, indent=2)
        insights_text = json.dumps(insights, indent=2)

        prompt = report_generation_prompt(
            lead_name=lead_name,
            company_name=company,
            website=website,
            research_data=research_text,
            analysis_data=analysis_text,
            insight_data=insights_text,
        )

        # Use higher temperature for more natural prose
        report_markdown = await llm.generate(prompt, temperature=0.4)

        log_entries.append(make_log_entry("report_generation", "completed", "Report generated"))
        nodes_completed = list(state.get("nodes_completed", []))
        nodes_completed.append("report_generation")

        return {
            **state,
            "report_markdown": report_markdown,
            "report_error": None,
            "log_entries": log_entries,
            "nodes_completed": nodes_completed,
            "current_node": "report_generation",
        }

    except Exception as exc:
        logger.error("Report generation failed: %s", exc, exc_info=True)
        log_entries.append(make_log_entry("report_generation", "failed", str(exc), error=str(exc)))

        # Generate minimal fallback report
        fallback_report = f"""# Business Audit Report — {company}

## Executive Summary

This report was generated for **{lead_name}** regarding **{company}** ({website}).
Due to a technical issue, some sections may be incomplete.

## Company Overview
- **Company:** {company}
- **Website:** {website}
- **Industry:** {research.get("industry", "N/A")}

## Key Findings
{chr(10).join(f"- {s}" for s in analysis.get("strengths", ["Data unavailable"]))}

## Recommendations
{chr(10).join(f"- {r}" for r in insights.get("recommendations", ["Contact us for a full analysis"]))}

---
*Report generated by Lead Intelligence AI*
"""

        return {
            **state,
            "report_markdown": fallback_report,
            "report_error": str(exc),
            "log_entries": log_entries,
            "current_node": "report_generation",
        }
